import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';

// @ts-ignore - the server build file is generated by `remix vite:build`
import * as build from '../build/server';
import type { AppLoadContext } from '@remix-run/server-runtime';

export const onRequest = createPagesFunctionHandler({
  build,
  mode: process.env.NODE_ENV,
  getLoadContext: (context: AppLoadContext) => ({
    env: context.env,
    cf: (context.request as unknown as any).cf as IncomingRequestCfProperties,
    // request: context.request,
  }),
  // getLoadContext: (context) => ({ env: context.env }),
});
