import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';

// @ts-ignore - the server build file is generated by `remix vite:build`
import * as build from '../build/server';
import { getLoadContext } from 'load-context';

export const onRequest = createPagesFunctionHandler({
  build,
  mode: process.env.NODE_ENV,
  // @ts-expect-error
  getLoadContext,
});
